apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: preprod
  labels:
   app: devops-app
spec:
  replicas: 3
  selector:
    matchlabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:      
      - name: devops-app
        image: vedant7669/devops-app:1.0
        ports:
          - containerPort: 80
  