server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # 🔥 strip /devops prefix
    location /devops/ {
        rewrite ^/devops/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }

    location = /devops {
        return 301 /devops/;
    }

    # optional safety
    location / {
        return 404;
    }
}