server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # serve static files correctly
    location /assets/ {
        try_files $uri =404;
    }

    # React routing
    location / {
        try_files $uri $uri/ /index.html;
    }
}